### ISSUE TITLE
tests pour info 121 à paris sud

### ISSUE THREAD

**Issue by HuxoD142** [PremierLangage/conceptexo#19]
Bonjour,

J'ai fais quelques tests aujourd'hui et je me retrouve fasse à une erreur que je ne comprend pas bien dont la trace est à la fin du message...
J'ai utiliser le builder créé par Nicolas Thiéry, et vu la trace le problème est dans le build... 
J'aimerais bien avoir accès au git pour faire plus facilement mes modifications et surtout pour que ce soit sauvegardé !

Merci pour votre aide !
Cordialement

_______________

Une erreur s'est produit sur la sandbox (exit code: -3, env: 868ccf11-422f-4508-a003-f23ffba7975e). Merci de prévenir votre professeur.

File 'processed.json' and 'pl.json' were not found in the environment after the execution of the build/before script.

Traceback (most recent call last):
  File "/srv/local/pl/premierlangage/server/serverpl/playexo/models.py", line 357, in get_exercise
    return self.get_pl(request, context)
  File "/srv/local/pl/premierlangage/server/serverpl/playexo/models.py", line 328, in get_pl
    self.build(request)
  File "/srv/local/pl/premierlangage/server/serverpl/playexo/models.py", line 250, in build
    raise SandboxError(msg)
playexo.exception.SandboxError: Une erreur s'est produit sur la sandbox (exit code: -3, env: 868ccf11-422f-4508-a003-f23ffba7975e). Merci de prévenir votre professeur.

File 'processed.json' and 'pl.json' were not found in the environment after the execution of the build/before script.

**Comment by HuxoD142** [comment]
Rebonjour,

Finalement j'ai trouvé mon erreur !
J'aimerais quand même bien avoir accès au Git si c'est possible !

Cordialement
Hugo Mlodecki
